<?php

use Illuminate\Database\Seeder;

use \App\PostalCode;

class PostalCodesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        PostalCode::insert(['id'=>'8341','name'=>'Adlešiči']);
PostalCode::insert(['id'=>'5270','name'=>'Ajdovščina']);
PostalCode::insert(['id'=>'6280','name'=>'Ankaran/Ancarano']);
PostalCode::insert(['id'=>'9253','name'=>'Apače']);
PostalCode::insert(['id'=>'8253','name'=>'Artiče']);
PostalCode::insert(['id'=>'4275','name'=>'Begunje na Gorenjskem']);
PostalCode::insert(['id'=>'1382','name'=>'Begunje pri Cerknici']);
PostalCode::insert(['id'=>'9231','name'=>'Beltinci']);
PostalCode::insert(['id'=>'2234','name'=>'Benedikt']);
PostalCode::insert(['id'=>'2345','name'=>'Bistrica ob Dravi']);
PostalCode::insert(['id'=>'3256','name'=>'Bistrica ob Sotli']);
PostalCode::insert(['id'=>'8259','name'=>'Bizeljsko']);
PostalCode::insert(['id'=>'1223','name'=>'Blagovica']);
PostalCode::insert(['id'=>'8283','name'=>'Blanca']);
PostalCode::insert(['id'=>'4260','name'=>'Bled']);
PostalCode::insert(['id'=>'4273','name'=>'Blejska Dobrava']);
PostalCode::insert(['id'=>'9265','name'=>'Bodonci']);
PostalCode::insert(['id'=>'9222','name'=>'Bogojina']);
PostalCode::insert(['id'=>'4263','name'=>'Bohinjska Bela']);
PostalCode::insert(['id'=>'4264','name'=>'Bohinjska Bistrica']);
PostalCode::insert(['id'=>'4265','name'=>'Bohinjsko jezero']);
PostalCode::insert(['id'=>'1353','name'=>'Borovnica']);
PostalCode::insert(['id'=>'8294','name'=>'Boštanj']);
PostalCode::insert(['id'=>'5230','name'=>'Bovec']);
PostalCode::insert(['id'=>'5295','name'=>'Branik']);
PostalCode::insert(['id'=>'3314','name'=>'Braslovče']);
PostalCode::insert(['id'=>'5223','name'=>'Breginj']);
PostalCode::insert(['id'=>'8280','name'=>'Brestanica']);
PostalCode::insert(['id'=>'2354','name'=>'Bresternica']);
PostalCode::insert(['id'=>'4243','name'=>'Brezje']);
PostalCode::insert(['id'=>'1351','name'=>'Brezovica pri Ljubljani']);
PostalCode::insert(['id'=>'8250','name'=>'Brežice']);
PostalCode::insert(['id'=>'4210','name'=>'Brnik - Aerodrom']);
PostalCode::insert(['id'=>'8321','name'=>'Brusnice']);
PostalCode::insert(['id'=>'3255','name'=>'Buče']);
PostalCode::insert(['id'=>'8276','name'=>'Bučka']);
PostalCode::insert(['id'=>'9261','name'=>'Cankova']);
PostalCode::insert(['id'=>'3000','name'=>'Celje']);
PostalCode::insert(['id'=>'3001','name'=>'Celje - poštni predali']);
PostalCode::insert(['id'=>'4207','name'=>'Cerklje na Gorenjskem']);
PostalCode::insert(['id'=>'8263','name'=>'Cerklje ob Krki']);
PostalCode::insert(['id'=>'1380','name'=>'Cerknica']);
PostalCode::insert(['id'=>'5282','name'=>'Cerkno']);
PostalCode::insert(['id'=>'2236','name'=>'Cerkvenjak']);
PostalCode::insert(['id'=>'2215','name'=>'Ceršak']);
PostalCode::insert(['id'=>'2326','name'=>'Cirkovce']);
PostalCode::insert(['id'=>'2282','name'=>'Cirkulane']);
PostalCode::insert(['id'=>'5273','name'=>'Col']);
PostalCode::insert(['id'=>'8251','name'=>'Čatež ob Savi']);
PostalCode::insert(['id'=>'1413','name'=>'Čemšenik']);
PostalCode::insert(['id'=>'5253','name'=>'Čepovan']);
PostalCode::insert(['id'=>'9232','name'=>'Črenšovci']);
PostalCode::insert(['id'=>'2393','name'=>'Črna na Koroškem']);
PostalCode::insert(['id'=>'6275','name'=>'Črni Kal']);
PostalCode::insert(['id'=>'5274','name'=>'Črni Vrh nad Idrijo']);
PostalCode::insert(['id'=>'5262','name'=>'Črniče']);
PostalCode::insert(['id'=>'8340','name'=>'Črnomelj']);
PostalCode::insert(['id'=>'6271','name'=>'Dekani']);
PostalCode::insert(['id'=>'5210','name'=>'Deskle']);
PostalCode::insert(['id'=>'2253','name'=>'Destrnik']);
PostalCode::insert(['id'=>'6215','name'=>'Divača']);
PostalCode::insert(['id'=>'1233','name'=>'Dob']);
PostalCode::insert(['id'=>'3224','name'=>'Dobje pri Planini']);
PostalCode::insert(['id'=>'8257','name'=>'Dobova']);
PostalCode::insert(['id'=>'1423','name'=>'Dobovec']);
PostalCode::insert(['id'=>'5263','name'=>'Dobravlje']);
PostalCode::insert(['id'=>'3204','name'=>'Dobrna']);
PostalCode::insert(['id'=>'8211','name'=>'Dobrnič']);
PostalCode::insert(['id'=>'1356','name'=>'Dobrova']);
PostalCode::insert(['id'=>'9223','name'=>'Dobrovnik/Dobronak']);
PostalCode::insert(['id'=>'5212','name'=>'Dobrovo v Brdih']);
PostalCode::insert(['id'=>'1431','name'=>'Dol pri Hrastniku']);
PostalCode::insert(['id'=>'1262','name'=>'Dol pri Ljubljani']);
PostalCode::insert(['id'=>'1273','name'=>'Dole pri Litiji']);
PostalCode::insert(['id'=>'1331','name'=>'Dolenja vas']);
PostalCode::insert(['id'=>'8350','name'=>'Dolenjske Toplice']);
PostalCode::insert(['id'=>'1230','name'=>'Domžale']);
PostalCode::insert(['id'=>'2252','name'=>'Dornava']);
PostalCode::insert(['id'=>'5294','name'=>'Dornberk']);
PostalCode::insert(['id'=>'1319','name'=>'Draga']);
PostalCode::insert(['id'=>'8343','name'=>'Dragatuš']);
PostalCode::insert(['id'=>'3222','name'=>'Dramlje']);
PostalCode::insert(['id'=>'2370','name'=>'Dravograd']);
PostalCode::insert(['id'=>'4203','name'=>'Duplje']);
PostalCode::insert(['id'=>'6221','name'=>'Dutovlje']);
PostalCode::insert(['id'=>'8361','name'=>'Dvor']);
PostalCode::insert(['id'=>'2343','name'=>'Fala']);
PostalCode::insert(['id'=>'9208','name'=>'Fokovci']);
PostalCode::insert(['id'=>'2313','name'=>'Fram']);
PostalCode::insert(['id'=>'3213','name'=>'Frankolovo']);
PostalCode::insert(['id'=>'1274','name'=>'Gabrovka']);
PostalCode::insert(['id'=>'8254','name'=>'Globoko']);
PostalCode::insert(['id'=>'5275','name'=>'Godovič']);
PostalCode::insert(['id'=>'4204','name'=>'Golnik']);
PostalCode::insert(['id'=>'3303','name'=>'Gomilsko']);
PostalCode::insert(['id'=>'4224','name'=>'Gorenja vas']);
PostalCode::insert(['id'=>'3263','name'=>'Gorica pri Slivnici']);
PostalCode::insert(['id'=>'2272','name'=>'Gorišnica']);
PostalCode::insert(['id'=>'9250','name'=>'Gornja Radgona']);
PostalCode::insert(['id'=>'3342','name'=>'Gornji Grad']);
PostalCode::insert(['id'=>'4282','name'=>'Gozd Martuljek']);
PostalCode::insert(['id'=>'6272','name'=>'Gračišče']);
PostalCode::insert(['id'=>'9264','name'=>'Grad']);
PostalCode::insert(['id'=>'8332','name'=>'Gradac']);
PostalCode::insert(['id'=>'1384','name'=>'Grahovo']);
PostalCode::insert(['id'=>'5242','name'=>'Grahovo ob Bači']);
PostalCode::insert(['id'=>'5251','name'=>'Grgar']);
PostalCode::insert(['id'=>'3302','name'=>'Griže']);
PostalCode::insert(['id'=>'3231','name'=>'Grobelno']);
PostalCode::insert(['id'=>'1290','name'=>'Grosuplje']);
PostalCode::insert(['id'=>'2288','name'=>'Hajdina']);
PostalCode::insert(['id'=>'8362','name'=>'Hinje']);
PostalCode::insert(['id'=>'2311','name'=>'Hoče']);
PostalCode::insert(['id'=>'9205','name'=>'Hodoš/Hodos']);
PostalCode::insert(['id'=>'1354','name'=>'Horjul']);
PostalCode::insert(['id'=>'1372','name'=>'Hotedršica']);
PostalCode::insert(['id'=>'1430','name'=>'Hrastnik']);
PostalCode::insert(['id'=>'6225','name'=>'Hruševje']);
PostalCode::insert(['id'=>'4276','name'=>'Hrušica']);
PostalCode::insert(['id'=>'5280','name'=>'Idrija']);
PostalCode::insert(['id'=>'1292','name'=>'Ig']);
PostalCode::insert(['id'=>'6250','name'=>'Ilirska Bistrica']);
PostalCode::insert(['id'=>'6251','name'=>'Ilirska Bistrica-Trnovo']);
PostalCode::insert(['id'=>'1295','name'=>'Ivančna Gorica']);
PostalCode::insert(['id'=>'2259','name'=>'Ivanjkovci']);
PostalCode::insert(['id'=>'1411','name'=>'Izlake']);
PostalCode::insert(['id'=>'6310','name'=>'Izola/Isola']);
PostalCode::insert(['id'=>'2222','name'=>'Jakobski Dol']);
PostalCode::insert(['id'=>'2221','name'=>'Jarenina']);
PostalCode::insert(['id'=>'6254','name'=>'Jelšane']);
PostalCode::insert(['id'=>'4270','name'=>'Jesenice']);
PostalCode::insert(['id'=>'8261','name'=>'Jesenice na Dolenjskem']);
PostalCode::insert(['id'=>'3273','name'=>'Jurklošter']);
PostalCode::insert(['id'=>'2223','name'=>'Jurovski Dol']);
PostalCode::insert(['id'=>'2256','name'=>'Juršinci']);
PostalCode::insert(['id'=>'5214','name'=>'Kal nad Kanalom']);
PostalCode::insert(['id'=>'3233','name'=>'Kalobje']);
PostalCode::insert(['id'=>'4246','name'=>'Kamna Gorica']);
PostalCode::insert(['id'=>'2351','name'=>'Kamnica']);
PostalCode::insert(['id'=>'1241','name'=>'Kamnik']);
PostalCode::insert(['id'=>'5213','name'=>'Kanal']);
PostalCode::insert(['id'=>'8258','name'=>'Kapele']);
PostalCode::insert(['id'=>'2362','name'=>'Kapla']);
PostalCode::insert(['id'=>'2325','name'=>'Kidričevo']);
PostalCode::insert(['id'=>'1412','name'=>'Kisovec']);
PostalCode::insert(['id'=>'6253','name'=>'Knežak']);
PostalCode::insert(['id'=>'5222','name'=>'Kobarid']);
PostalCode::insert(['id'=>'9227','name'=>'Kobilje']);
PostalCode::insert(['id'=>'1330','name'=>'Kočevje']);
PostalCode::insert(['id'=>'1338','name'=>'Kočevska Reka']);
PostalCode::insert(['id'=>'2276','name'=>'Kog']);
PostalCode::insert(['id'=>'5211','name'=>'Kojsko']);
PostalCode::insert(['id'=>'6223','name'=>'Komen']);
PostalCode::insert(['id'=>'1218','name'=>'Komenda']);
PostalCode::insert(['id'=>'6000','name'=>'Koper/Capodistria']);
PostalCode::insert(['id'=>'6001','name'=>'Koper/Capodistria - poštni predali']);
PostalCode::insert(['id'=>'8282','name'=>'Koprivnica']);
PostalCode::insert(['id'=>'5296','name'=>'Kostanjevica na Krasu']);
PostalCode::insert(['id'=>'8311','name'=>'Kostanjevica na Krki']);
PostalCode::insert(['id'=>'1336','name'=>'Kostel']);
PostalCode::insert(['id'=>'6256','name'=>'Košana']);
PostalCode::insert(['id'=>'2394','name'=>'Kotlje']);
PostalCode::insert(['id'=>'6240','name'=>'Kozina']);
PostalCode::insert(['id'=>'3260','name'=>'Kozje']);
PostalCode::insert(['id'=>'4000','name'=>'Kranj']);
PostalCode::insert(['id'=>'4001','name'=>'Kranj - poštni predali']);
PostalCode::insert(['id'=>'4280','name'=>'Kranjska Gora']);
PostalCode::insert(['id'=>'1281','name'=>'Kresnice']);
PostalCode::insert(['id'=>'4294','name'=>'Križe']);
PostalCode::insert(['id'=>'9206','name'=>'Križevci']);
PostalCode::insert(['id'=>'9242','name'=>'Križevci pri Ljutomeru']);
PostalCode::insert(['id'=>'1301','name'=>'Krka']);
PostalCode::insert(['id'=>'8296','name'=>'Krmelj']);
PostalCode::insert(['id'=>'4245','name'=>'Kropa']);
PostalCode::insert(['id'=>'8262','name'=>'Krška vas']);
PostalCode::insert(['id'=>'8270','name'=>'Krško']);
PostalCode::insert(['id'=>'9263','name'=>'Kuzma']);
PostalCode::insert(['id'=>'2318','name'=>'Laporje']);
PostalCode::insert(['id'=>'3270','name'=>'Laško']);
PostalCode::insert(['id'=>'1219','name'=>'Laze v Tuhinju']);
PostalCode::insert(['id'=>'2230','name'=>'Lenart v Slovenskih goricah']);
PostalCode::insert(['id'=>'9220','name'=>'Lendava/Lendva']);
PostalCode::insert(['id'=>'4248','name'=>'Lesce']);
PostalCode::insert(['id'=>'3261','name'=>'Lesično']);
PostalCode::insert(['id'=>'8273','name'=>'Leskovec pri Krškem']);
PostalCode::insert(['id'=>'2372','name'=>'Libeliče']);
PostalCode::insert(['id'=>'2341','name'=>'Limbuš']);
PostalCode::insert(['id'=>'1270','name'=>'Litija']);
PostalCode::insert(['id'=>'3202','name'=>'Ljubečna']);
PostalCode::insert(['id'=>'1000','name'=>'Ljubljana']);
PostalCode::insert(['id'=>'1001','name'=>'Ljubljana - poštni predali']);
PostalCode::insert(['id'=>'1231','name'=>'Ljubljana - Črnuče']);
PostalCode::insert(['id'=>'1261','name'=>'Ljubljana - Dobrunje']);
PostalCode::insert(['id'=>'1260','name'=>'Ljubljana - Polje']);
PostalCode::insert(['id'=>'1210','name'=>'Ljubljana - Šentvid']);
PostalCode::insert(['id'=>'1211','name'=>'Ljubljana - Šmartno']);
PostalCode::insert(['id'=>'3333','name'=>'Ljubno ob Savinji']);
PostalCode::insert(['id'=>'9240','name'=>'Ljutomer']);
PostalCode::insert(['id'=>'3215','name'=>'Loče']);
PostalCode::insert(['id'=>'5231','name'=>'Log pod Mangartom']);
PostalCode::insert(['id'=>'1358','name'=>'Log pri Brezovici']);
PostalCode::insert(['id'=>'1370','name'=>'Logatec']);
PostalCode::insert(['id'=>'1371','name'=>'Logatec']);
PostalCode::insert(['id'=>'1434','name'=>'Loka pri Zidanem Mostu']);
PostalCode::insert(['id'=>'3223','name'=>'Loka pri Žusmu']);
PostalCode::insert(['id'=>'6219','name'=>'Lokev']);
PostalCode::insert(['id'=>'1318','name'=>'Loški Potok']);
PostalCode::insert(['id'=>'2324','name'=>'Lovrenc na Dravskem polju']);
PostalCode::insert(['id'=>'2344','name'=>'Lovrenc na Pohorju']);
PostalCode::insert(['id'=>'3334','name'=>'Luče']);
PostalCode::insert(['id'=>'1225','name'=>'Lukovica']);
PostalCode::insert(['id'=>'9202','name'=>'Mačkovci']);
PostalCode::insert(['id'=>'2322','name'=>'Majšperk']);
PostalCode::insert(['id'=>'2321','name'=>'Makole']);
PostalCode::insert(['id'=>'9243','name'=>'Mala Nedelja']);
PostalCode::insert(['id'=>'2229','name'=>'Malečnik']);
PostalCode::insert(['id'=>'6273','name'=>'Marezige']);
PostalCode::insert(['id'=>'2000','name'=>'Maribor']);
PostalCode::insert(['id'=>'2001','name'=>'Maribor - poštni predali']);
PostalCode::insert(['id'=>'2206','name'=>'Marjeta na Dravskem polju']);
PostalCode::insert(['id'=>'2281','name'=>'Markovci']);
PostalCode::insert(['id'=>'9221','name'=>'Martjanci']);
PostalCode::insert(['id'=>'6242','name'=>'Materija']);
PostalCode::insert(['id'=>'4211','name'=>'Mavčiče']);
PostalCode::insert(['id'=>'1215','name'=>'Medvode']);
PostalCode::insert(['id'=>'1234','name'=>'Mengeš']);
PostalCode::insert(['id'=>'8330','name'=>'Metlika']);
PostalCode::insert(['id'=>'2392','name'=>'Mežica']);
PostalCode::insert(['id'=>'2204','name'=>'Miklavž na Dravskem polju']);
PostalCode::insert(['id'=>'2275','name'=>'Miklavž pri Ormožu']);
PostalCode::insert(['id'=>'5291','name'=>'Miren']);
PostalCode::insert(['id'=>'8233','name'=>'Mirna']);
PostalCode::insert(['id'=>'8216','name'=>'Mirna Peč']);
PostalCode::insert(['id'=>'2382','name'=>'Mislinja']);
PostalCode::insert(['id'=>'4281','name'=>'Mojstrana']);
PostalCode::insert(['id'=>'8230','name'=>'Mokronog']);
PostalCode::insert(['id'=>'1251','name'=>'Moravče']);
PostalCode::insert(['id'=>'9226','name'=>'Moravske Toplice']);
PostalCode::insert(['id'=>'5216','name'=>'Most na Soči']);
PostalCode::insert(['id'=>'1221','name'=>'Motnik']);
PostalCode::insert(['id'=>'3330','name'=>'Mozirje']);
PostalCode::insert(['id'=>'9000','name'=>'Murska Sobota']);
PostalCode::insert(['id'=>'9001','name'=>'Murska Sobota - poštni predali']);
PostalCode::insert(['id'=>'2366','name'=>'Muta']);
PostalCode::insert(['id'=>'4202','name'=>'Naklo']);
PostalCode::insert(['id'=>'3331','name'=>'Nazarje']);
PostalCode::insert(['id'=>'1357','name'=>'Notranje Gorice']);
PostalCode::insert(['id'=>'3203','name'=>'Nova Cerkev']);
PostalCode::insert(['id'=>'5000','name'=>'Nova Gorica']);
PostalCode::insert(['id'=>'5001','name'=>'Nova Gorica - poštni predali']);
PostalCode::insert(['id'=>'1385','name'=>'Nova vas']);
PostalCode::insert(['id'=>'8000','name'=>'Novo mesto']);
PostalCode::insert(['id'=>'8001','name'=>'Novo mesto - poštni predali']);
PostalCode::insert(['id'=>'6243','name'=>'Obrov']);
PostalCode::insert(['id'=>'9233','name'=>'Odranci']);
PostalCode::insert(['id'=>'2317','name'=>'Oplotnica']);
PostalCode::insert(['id'=>'2312','name'=>'Orehova vas']);
PostalCode::insert(['id'=>'2270','name'=>'Ormož']);
PostalCode::insert(['id'=>'1316','name'=>'Ortnek']);
PostalCode::insert(['id'=>'1337','name'=>'Osilnica']);
PostalCode::insert(['id'=>'8222','name'=>'Otočec']);
PostalCode::insert(['id'=>'2361','name'=>'Ožbalt']);
PostalCode::insert(['id'=>'2231','name'=>'Pernica']);
PostalCode::insert(['id'=>'2211','name'=>'Pesnica pri Mariboru']);
PostalCode::insert(['id'=>'9203','name'=>'Petrovci']);
PostalCode::insert(['id'=>'3301','name'=>'Petrovče']);
PostalCode::insert(['id'=>'6330','name'=>'Piran/Pirano']);
PostalCode::insert(['id'=>'8255','name'=>'Pišece']);
PostalCode::insert(['id'=>'6257','name'=>'Pivka']);
PostalCode::insert(['id'=>'6232','name'=>'Planina']);
PostalCode::insert(['id'=>'3225','name'=>'Planina pri Sevnici']);
PostalCode::insert(['id'=>'6276','name'=>'Pobegi']);
PostalCode::insert(['id'=>'8312','name'=>'Podbočje']);
PostalCode::insert(['id'=>'5243','name'=>'Podbrdo']);
PostalCode::insert(['id'=>'3254','name'=>'Podčetrtek']);
PostalCode::insert(['id'=>'2273','name'=>'Podgorci']);
PostalCode::insert(['id'=>'6216','name'=>'Podgorje']);
PostalCode::insert(['id'=>'2381','name'=>'Podgorje pri Slovenj Gradcu']);
PostalCode::insert(['id'=>'6244','name'=>'Podgrad']);
PostalCode::insert(['id'=>'1414','name'=>'Podkum']);
PostalCode::insert(['id'=>'2286','name'=>'Podlehnik']);
PostalCode::insert(['id'=>'5272','name'=>'Podnanos']);
PostalCode::insert(['id'=>'4244','name'=>'Podnart']);
PostalCode::insert(['id'=>'3241','name'=>'Podplat']);
PostalCode::insert(['id'=>'3257','name'=>'Podsreda']);
PostalCode::insert(['id'=>'2363','name'=>'Podvelka']);
PostalCode::insert(['id'=>'2208','name'=>'Pohorje']);
PostalCode::insert(['id'=>'2257','name'=>'Polenšak']);
PostalCode::insert(['id'=>'1355','name'=>'Polhov Gradec']);
PostalCode::insert(['id'=>'4223','name'=>'Poljane nad Škofjo Loko']);
PostalCode::insert(['id'=>'2319','name'=>'Poljčane']);
PostalCode::insert(['id'=>'1272','name'=>'Polšnik']);
PostalCode::insert(['id'=>'3313','name'=>'Polzela']);
PostalCode::insert(['id'=>'3232','name'=>'Ponikva']);
PostalCode::insert(['id'=>'6320','name'=>'Portorož/Portorose']);
PostalCode::insert(['id'=>'6230','name'=>'Postojna']);
PostalCode::insert(['id'=>'2331','name'=>'Pragersko']);
PostalCode::insert(['id'=>'3312','name'=>'Prebold']);
PostalCode::insert(['id'=>'4205','name'=>'Preddvor']);
PostalCode::insert(['id'=>'6255','name'=>'Prem']);
PostalCode::insert(['id'=>'1352','name'=>'Preserje']);
PostalCode::insert(['id'=>'6258','name'=>'Prestranek']);
PostalCode::insert(['id'=>'2391','name'=>'Prevalje']);
PostalCode::insert(['id'=>'3262','name'=>'Prevorje']);
PostalCode::insert(['id'=>'1276','name'=>'Primskovo']);
PostalCode::insert(['id'=>'3253','name'=>'Pristava pri Mestinju']);
PostalCode::insert(['id'=>'9207','name'=>'Prosenjakovci/Partosfalva']);
PostalCode::insert(['id'=>'5297','name'=>'Prvačina']);
PostalCode::insert(['id'=>'2250','name'=>'Ptuj']);
PostalCode::insert(['id'=>'2323','name'=>'Ptujska Gora']);
PostalCode::insert(['id'=>'9201','name'=>'Puconci']);
PostalCode::insert(['id'=>'2327','name'=>'Rače']);
PostalCode::insert(['id'=>'1433','name'=>'Radeče']);
PostalCode::insert(['id'=>'9252','name'=>'Radenci']);
PostalCode::insert(['id'=>'2360','name'=>'Radlje ob Dravi']);
PostalCode::insert(['id'=>'1235','name'=>'Radomlje']);
PostalCode::insert(['id'=>'4240','name'=>'Radovljica']);
PostalCode::insert(['id'=>'8274','name'=>'Raka']);
PostalCode::insert(['id'=>'1381','name'=>'Rakek']);
PostalCode::insert(['id'=>'4283','name'=>'Rateče - Planica']);
PostalCode::insert(['id'=>'2390','name'=>'Ravne na Koroškem']);
PostalCode::insert(['id'=>'9246','name'=>'Razkrižje']);
PostalCode::insert(['id'=>'3332','name'=>'Rečica ob Savinji']);
PostalCode::insert(['id'=>'5292','name'=>'Renče']);
PostalCode::insert(['id'=>'1310','name'=>'Ribnica']);
PostalCode::insert(['id'=>'2364','name'=>'Ribnica na Pohorju']);
PostalCode::insert(['id'=>'3272','name'=>'Rimske Toplice']);
PostalCode::insert(['id'=>'1314','name'=>'Rob']);
PostalCode::insert(['id'=>'5215','name'=>'Ročinj']);
PostalCode::insert(['id'=>'3250','name'=>'Rogaška Slatina']);
PostalCode::insert(['id'=>'9262','name'=>'Rogašovci']);
PostalCode::insert(['id'=>'3252','name'=>'Rogatec']);
PostalCode::insert(['id'=>'1373','name'=>'Rovte']);
PostalCode::insert(['id'=>'2342','name'=>'Ruše']);
PostalCode::insert(['id'=>'1282','name'=>'Sava']);
PostalCode::insert(['id'=>'6333','name'=>'Sečovlje/Sicciole']);
PostalCode::insert(['id'=>'4227','name'=>'Selca']);
PostalCode::insert(['id'=>'2352','name'=>'Selnica ob Dravi']);
PostalCode::insert(['id'=>'8333','name'=>'Semič']);
PostalCode::insert(['id'=>'8281','name'=>'Senovo']);
PostalCode::insert(['id'=>'6224','name'=>'Senožeče']);
PostalCode::insert(['id'=>'8290','name'=>'Sevnica']);
PostalCode::insert(['id'=>'6210','name'=>'Sežana']);
PostalCode::insert(['id'=>'2214','name'=>'Sladki Vrh']);
PostalCode::insert(['id'=>'5283','name'=>'Slap ob Idrijci']);
PostalCode::insert(['id'=>'2380','name'=>'Slovenj Gradec']);
PostalCode::insert(['id'=>'2310','name'=>'Slovenska Bistrica']);
PostalCode::insert(['id'=>'3210','name'=>'Slovenske Konjice']);
PostalCode::insert(['id'=>'1216','name'=>'Smlednik']);
PostalCode::insert(['id'=>'5232','name'=>'Soča']);
PostalCode::insert(['id'=>'1317','name'=>'Sodražica']);
PostalCode::insert(['id'=>'3335','name'=>'Solčava']);
PostalCode::insert(['id'=>'5250','name'=>'Solkan']);
PostalCode::insert(['id'=>'4229','name'=>'Sorica']);
PostalCode::insert(['id'=>'4225','name'=>'Sovodenj']);
PostalCode::insert(['id'=>'5281','name'=>'Spodnja Idrija']);
PostalCode::insert(['id'=>'2241','name'=>'Spodnji Duplek']);
PostalCode::insert(['id'=>'9245','name'=>'Spodnji Ivanjci']);
PostalCode::insert(['id'=>'2277','name'=>'Središče ob Dravi']);
PostalCode::insert(['id'=>'4267','name'=>'Srednja vas v Bohinju']);
PostalCode::insert(['id'=>'8256','name'=>'Sromlje']);
PostalCode::insert(['id'=>'5224','name'=>'Srpenica']);
PostalCode::insert(['id'=>'1242','name'=>'Stahovica']);
PostalCode::insert(['id'=>'1332','name'=>'Stara Cerkev']);
PostalCode::insert(['id'=>'8342','name'=>'Stari trg ob Kolpi']);
PostalCode::insert(['id'=>'1386','name'=>'Stari trg pri Ložu']);
PostalCode::insert(['id'=>'2205','name'=>'Starše']);
PostalCode::insert(['id'=>'2289','name'=>'Stoperce']);
PostalCode::insert(['id'=>'8322','name'=>'Stopiče']);
PostalCode::insert(['id'=>'3206','name'=>'Stranice']);
PostalCode::insert(['id'=>'8351','name'=>'Straža']);
PostalCode::insert(['id'=>'1313','name'=>'Struge']);
PostalCode::insert(['id'=>'8293','name'=>'Studenec']);
PostalCode::insert(['id'=>'8331','name'=>'Suhor']);
PostalCode::insert(['id'=>'2233','name'=>'Sv. Ana v Slovenskih goricah']);
PostalCode::insert(['id'=>'2235','name'=>'Sv. Trojica v Slovenskih goricah']);
PostalCode::insert(['id'=>'2353','name'=>'Sveti Duh na Ostrem Vrhu']);
PostalCode::insert(['id'=>'9244','name'=>'Sveti Jurij ob Ščavnici']);
PostalCode::insert(['id'=>'3264','name'=>'Sveti Štefan']);
PostalCode::insert(['id'=>'2258','name'=>'Sveti Tomaž']);
PostalCode::insert(['id'=>'9204','name'=>'Šalovci']);
PostalCode::insert(['id'=>'5261','name'=>'Šempas']);
PostalCode::insert(['id'=>'5290','name'=>'Šempeter pri Gorici']);
PostalCode::insert(['id'=>'3311','name'=>'Šempeter v Savinjski dolini']);
PostalCode::insert(['id'=>'4208','name'=>'Šenčur']);
PostalCode::insert(['id'=>'2212','name'=>'Šentilj v Slovenskih goricah']);
PostalCode::insert(['id'=>'8297','name'=>'Šentjanž']);
PostalCode::insert(['id'=>'2373','name'=>'Šentjanž pri Dravogradu']);
PostalCode::insert(['id'=>'8310','name'=>'Šentjernej']);
PostalCode::insert(['id'=>'3230','name'=>'Šentjur']);
PostalCode::insert(['id'=>'3271','name'=>'Šentrupert']);
PostalCode::insert(['id'=>'8232','name'=>'Šentrupert']);
PostalCode::insert(['id'=>'1296','name'=>'Šentvid pri Stični']);
PostalCode::insert(['id'=>'8275','name'=>'Škocjan']);
PostalCode::insert(['id'=>'6281','name'=>'Škofije']);
PostalCode::insert(['id'=>'4220','name'=>'Škofja Loka']);
PostalCode::insert(['id'=>'3211','name'=>'Škofja vas']);
PostalCode::insert(['id'=>'1291','name'=>'Škofljica']);
PostalCode::insert(['id'=>'6274','name'=>'Šmarje']);
PostalCode::insert(['id'=>'1293','name'=>'Šmarje - Sap']);
PostalCode::insert(['id'=>'3240','name'=>'Šmarje pri Jelšah']);
PostalCode::insert(['id'=>'8220','name'=>'Šmarješke Toplice']);
PostalCode::insert(['id'=>'2315','name'=>'Šmartno na Pohorju']);
PostalCode::insert(['id'=>'3341','name'=>'Šmartno ob Dreti']);
PostalCode::insert(['id'=>'3327','name'=>'Šmartno ob Paki']);
PostalCode::insert(['id'=>'1275','name'=>'Šmartno pri Litiji']);
PostalCode::insert(['id'=>'2383','name'=>'Šmartno pri Slovenj Gradcu']);
PostalCode::insert(['id'=>'3201','name'=>'Šmartno v Rožni dolini']);
PostalCode::insert(['id'=>'3325','name'=>'Šoštanj']);
PostalCode::insert(['id'=>'6222','name'=>'Štanjel']);
PostalCode::insert(['id'=>'3220','name'=>'Štore']);
PostalCode::insert(['id'=>'3304','name'=>'Tabor']);
PostalCode::insert(['id'=>'3221','name'=>'Teharje']);
PostalCode::insert(['id'=>'9251','name'=>'Tišina']);
PostalCode::insert(['id'=>'5220','name'=>'Tolmin']);
PostalCode::insert(['id'=>'3326','name'=>'Topolšica']);
PostalCode::insert(['id'=>'2371','name'=>'Trbonje']);
PostalCode::insert(['id'=>'1420','name'=>'Trbovlje']);
PostalCode::insert(['id'=>'8231','name'=>'Trebelno']);
PostalCode::insert(['id'=>'8210','name'=>'Trebnje']);
PostalCode::insert(['id'=>'5252','name'=>'Trnovo pri Gorici']);
PostalCode::insert(['id'=>'2254','name'=>'Trnovska vas']);
PostalCode::insert(['id'=>'1222','name'=>'Trojane']);
PostalCode::insert(['id'=>'1236','name'=>'Trzin']);
PostalCode::insert(['id'=>'4290','name'=>'Tržič']);
PostalCode::insert(['id'=>'8295','name'=>'Tržišče']);
PostalCode::insert(['id'=>'1311','name'=>'Turjak']);
PostalCode::insert(['id'=>'9224','name'=>'Turnišče']);
PostalCode::insert(['id'=>'8323','name'=>'Uršna sela']);
PostalCode::insert(['id'=>'1252','name'=>'Vače']);
PostalCode::insert(['id'=>'3320','name'=>'Velenje']);
PostalCode::insert(['id'=>'3322','name'=>'Velenje - poštni predali']);
PostalCode::insert(['id'=>'8212','name'=>'Velika Loka']);
PostalCode::insert(['id'=>'2274','name'=>'Velika Nedelja']);
PostalCode::insert(['id'=>'9225','name'=>'Velika Polana']);
PostalCode::insert(['id'=>'1315','name'=>'Velike Lašče']);
PostalCode::insert(['id'=>'8213','name'=>'Veliki Gaber']);
PostalCode::insert(['id'=>'9241','name'=>'Veržej']);
PostalCode::insert(['id'=>'1312','name'=>'Videm - Dobrepolje']);
PostalCode::insert(['id'=>'2284','name'=>'Videm pri Ptuju']);
PostalCode::insert(['id'=>'8344','name'=>'Vinica']);
PostalCode::insert(['id'=>'5271','name'=>'Vipava']);
PostalCode::insert(['id'=>'4212','name'=>'Visoko']);
PostalCode::insert(['id'=>'1294','name'=>'Višnja Gora']);
PostalCode::insert(['id'=>'3205','name'=>'Vitanje']);
PostalCode::insert(['id'=>'2255','name'=>'Vitomarci']);
PostalCode::insert(['id'=>'1217','name'=>'Vodice']);
PostalCode::insert(['id'=>'3212','name'=>'Vojnik']);
PostalCode::insert(['id'=>'5293','name'=>'Volčja Draga']);
PostalCode::insert(['id'=>'2232','name'=>'Voličina']);
PostalCode::insert(['id'=>'3305','name'=>'Vransko']);
PostalCode::insert(['id'=>'6217','name'=>'Vremski Britof']);
PostalCode::insert(['id'=>'1360','name'=>'Vrhnika']);
PostalCode::insert(['id'=>'2365','name'=>'Vuhred']);
PostalCode::insert(['id'=>'2367','name'=>'Vuzenica']);
PostalCode::insert(['id'=>'8292','name'=>'Zabukovje']);
PostalCode::insert(['id'=>'1410','name'=>'Zagorje ob Savi']);
PostalCode::insert(['id'=>'1303','name'=>'Zagradec']);
PostalCode::insert(['id'=>'2283','name'=>'Zavrč']);
PostalCode::insert(['id'=>'8272','name'=>'Zdole']);
PostalCode::insert(['id'=>'4201','name'=>'Zgornja Besnica']);
PostalCode::insert(['id'=>'2242','name'=>'Zgornja Korena']);
PostalCode::insert(['id'=>'2201','name'=>'Zgornja Kungota']);
PostalCode::insert(['id'=>'2316','name'=>'Zgornja Ložnica']);
PostalCode::insert(['id'=>'2314','name'=>'Zgornja Polskava']);
PostalCode::insert(['id'=>'2213','name'=>'Zgornja Velka']);
PostalCode::insert(['id'=>'4247','name'=>'Zgornje Gorje']);
PostalCode::insert(['id'=>'4206','name'=>'Zgornje Jezersko']);
PostalCode::insert(['id'=>'2285','name'=>'Zgornji Leskovec']);
PostalCode::insert(['id'=>'1432','name'=>'Zidani Most']);
PostalCode::insert(['id'=>'3214','name'=>'Zreče']);
PostalCode::insert(['id'=>'4209','name'=>'Žabnica']);
PostalCode::insert(['id'=>'3310','name'=>'Žalec']);
PostalCode::insert(['id'=>'4228','name'=>'Železniki']);
PostalCode::insert(['id'=>'2287','name'=>'Žetale']);
PostalCode::insert(['id'=>'4226','name'=>'Žiri']);
PostalCode::insert(['id'=>'4274','name'=>'Žirovnica']);
PostalCode::insert(['id'=>'8360','name'=>'Žužemberk']);
PostalCode::insert(['id'=>'3505','name'=>'Celje Merkur']);
PostalCode::insert(['id'=>'3600','name'=>'Celje Pošta Slovenije, PE Celje']);
PostalCode::insert(['id'=>'6503','name'=>'Koper Adriatic Slovenica, Zavarovalna družba']);
PostalCode::insert(['id'=>'6502','name'=>'Koper Banka Koper']);
PostalCode::insert(['id'=>'6504','name'=>'Koper Intereuropa']);
PostalCode::insert(['id'=>'6501','name'=>'Koper Luka Koper']);
PostalCode::insert(['id'=>'6600','name'=>'Koper Pošta Slovenije, PE Koper']);
PostalCode::insert(['id'=>'6200','name'=>'Koper Pošta Slovenije, PPP Koper']);
PostalCode::insert(['id'=>'4200','name'=>'Kranj Pošta Slovenije, PPP Šenčur']);
PostalCode::insert(['id'=>'4502','name'=>'Kranj Sava']);
PostalCode::insert(['id'=>'1002','name'=>'Ljubljana Pošta Slovenije, PE PLC, PLC Ljubljana']);
PostalCode::insert(['id'=>'1517','name'=>'Ljubljana Abanka Vipa']);
PostalCode::insert(['id'=>'1505','name'=>'Ljubljana Banka Slovenije']);
PostalCode::insert(['id'=>'1533','name'=>'Ljubljana BTC']);
PostalCode::insert(['id'=>'1512','name'=>'Ljubljana Cankarjeva založba']);
PostalCode::insert(['id'=>'1524','name'=>'Ljubljana Carinarnica Ljubljana']);
PostalCode::insert(['id'=>'1523','name'=>'Ljubljana Carinska uprava Republike Slovenije']);
PostalCode::insert(['id'=>'1522','name'=>'Ljubljana Chemo']);
PostalCode::insert(['id'=>'1510','name'=>'Ljubljana Dnevnik']);
PostalCode::insert(['id'=>'1509','name'=>'Ljubljana Delo']);
PostalCode::insert(['id'=>'1538','name'=>'Ljubljana DZS']);
PostalCode::insert(['id'=>'1516','name'=>'Ljubljana Elektro Ljubljana']);
PostalCode::insert(['id'=>'1528','name'=>'Ljubljana Emona']);
PostalCode::insert(['id'=>'1540','name'=>'Ljubljana EPPS - Elektronsko pismo Pošte Slovenije']);
PostalCode::insert(['id'=>'1504','name'=>'Ljubljana Gospodarska zbornica Slovenije']);
PostalCode::insert(['id'=>'1521','name'=>'Ljubljana Iskra Invest']);
PostalCode::insert(['id'=>'1545','name'=>'Ljubljana Kanal A']);
PostalCode::insert(['id'=>'1542','name'=>'Ljubljana KDD - Centralna klirinško depotna družba']);
PostalCode::insert(['id'=>'1525','name'=>'Ljubljana Klinični center Ljubljana']);
PostalCode::insert(['id'=>'1544','name'=>'Ljubljana Droga Kolinska']);
PostalCode::insert(['id'=>'1514','name'=>'Ljubljana Kompas']);
PostalCode::insert(['id'=>'1526','name'=>'Ljubljana Lek']);
PostalCode::insert(['id'=>'1502','name'=>'Ljubljana Ministrstvo za finance']);
PostalCode::insert(['id'=>'1501','name'=>'Ljubljana Ministrstvo za notranje zadeve']);
PostalCode::insert(['id'=>'1535','name'=>'Ljubljana Ministrstvo za promet']);
PostalCode::insert(['id'=>'1536','name'=>'Ljubljana Mladinska knjiga Založba']);
PostalCode::insert(['id'=>'1537','name'=>'Ljubljana Mobitel']);
PostalCode::insert(['id'=>'1520','name'=>'Ljubljana Nova Ljubljanska banka']);
PostalCode::insert(['id'=>'1534','name'=>'Ljubljana Okrajno sodišče v Ljubljani']);
PostalCode::insert(['id'=>'1503','name'=>'Ljubljana Okrožno sodišče v Ljubljani']);
PostalCode::insert(['id'=>'1527','name'=>'Ljubljana Petrol']);
PostalCode::insert(['id'=>'1600','name'=>'Ljubljana Pošta Slovenije, PE Ljubljana']);
PostalCode::insert(['id'=>'1550','name'=>'Ljubljana RTV Slovenija']);
PostalCode::insert(['id'=>'1532','name'=>'Ljubljana Salamonov oglasnik']);
PostalCode::insert(['id'=>'1513','name'=>'Ljubljana SKB banka']);
PostalCode::insert(['id'=>'1511','name'=>'Ljubljana Slovenijales']);
PostalCode::insert(['id'=>'1506','name'=>'Ljubljana Slovenske železnice']);
PostalCode::insert(['id'=>'1519','name'=>'Ljubljana SPL Ljubljana']);
PostalCode::insert(['id'=>'1543','name'=>'Ljubljana Športna loterija']);
PostalCode::insert(['id'=>'1546','name'=>'Ljubljana Telekom Slovenije']);
PostalCode::insert(['id'=>'1547','name'=>'Ljubljana Telekom Slovenije, PE Ljubljana']);
PostalCode::insert(['id'=>'1518','name'=>'Ljubljana ZPIZ, Zavod za pokoj. in inval. zav. Slov.']);
PostalCode::insert(['id'=>'1507','name'=>'Ljubljana ZZZS, Zavod za zdrav. zav. Slov.']);
PostalCode::insert(['id'=>'1529','name'=>'Ljubljana Žito']);
PostalCode::insert(['id'=>'2002','name'=>'Maribor Pošta Slovenije, PE PLC, PLC Maribor']);
PostalCode::insert(['id'=>'2502','name'=>'Maribor FURS, Finančni urad Maribor']);
PostalCode::insert(['id'=>'2509','name'=>'Maribor Elektro Maribor']);
PostalCode::insert(['id'=>'2506','name'=>'Maribor Henkel Slovenija']);
PostalCode::insert(['id'=>'2505','name'=>'Maribor Nova Kreditna banka Maribor']);
PostalCode::insert(['id'=>'2503','name'=>'Maribor Okrožno sodišče v Mariboru']);
PostalCode::insert(['id'=>'2508','name'=>'Maribor Okrajno sodišče v Mariboru']);
PostalCode::insert(['id'=>'2500','name'=>'Maribor Pošta Slovenije, uprava']);
PostalCode::insert(['id'=>'2600','name'=>'Maribor Pošta Slovenije, PE Maribor']);
PostalCode::insert(['id'=>'2607','name'=>'Maribor Pošta Slovenije, Center za digitalizacijo']);
PostalCode::insert(['id'=>'2609','name'=>'Maribor Pošta Slovenije, PE PLC Maribor, Skladiščna logistika']);
PostalCode::insert(['id'=>'2610','name'=>'Maribor Pošta Slovenije, Centralna RA pisarna']);
PostalCode::insert(['id'=>'2501','name'=>'Maribor Upravna enota Maribor']);
PostalCode::insert(['id'=>'2504','name'=>'Maribor Večer']);
PostalCode::insert(['id'=>'2507','name'=>'Maribor Zavarovalnica Maribor']);
PostalCode::insert(['id'=>'9501','name'=>'Murska Sobota Mura']);
PostalCode::insert(['id'=>'4501','name'=>'Naklo Merkur']);
PostalCode::insert(['id'=>'8501','name'=>'Novo mesto Krka']);
PostalCode::insert(['id'=>'9502','name'=>'Radenci Radenska d.d.']);
PostalCode::insert(['id'=>'3503','name'=>'Velenje Gorenje']);
PostalCode::insert(['id'=>'3504','name'=>'Velenje ERA']);
    }
}
